optimization:
  radius: 0.2
  max_steps: 10
  step_improvement_threshold: 0.01
  max_threads: 1


ik_solver:
  name: MoveItScannabilitySolver
  distance_threshold: 0.0
  planning_group: manipulator
  collision_mesh_filename: package://reach_ros/demo/config/part.ply
  touch_links: []
  use_approximate_solution: false
  sensor_frame_name: tcp
  min_dist: 0.0
  max_dist: 0.5
  opt_dist: 0.1
  angle_threshold: 0.3
  opt_angle: 0.0
  sensor_fov_x: 0.8
  sensor_fov_y: 0.45

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ScannabilityMoveIt
      planning_group: manipulator
      sensor_frame_name: tool0
      min_dist: 0.0
      max_dist: 0.5
      opt_dist: 0.1
      angle_threshold: 0.3
      opt_angle: 0.0
      sensor_fov_x: 0.8
      sensor_fov_y: 0.45


display:
  name: ROSDisplay
  collision_mesh_filename: package://reach_ros/demo/config/part.ply
  kinematic_base_frame: base_link
  marker_scale: 0.05

target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_ros/demo/config/part.pcd

logger:
  name: BoostProgressConsoleLogger
