planning_group: &planning_group scan
collision_mesh_filename: &collision_mesh_filename package://reach_ros/demo/config/part.ply

optimization:
  radius: 0.2
  max_steps: 10
  step_improvement_threshold: 0.01
  max_threads: 1


ik_solver:
  name: MoveItScannabilitySolver
  distance_threshold: 0.0
  planning_group: *planning_group
  collision_mesh_filename: *collision_mesh_filename
  touch_links: []
  use_approximate_solution: false
  sensor_frame_name: tcp
  opt_dist: 0.1
  opt_angle: 0.0
  check_line_of_sight: true
  line_of_sight_in_cost_function: true
  publish_line_of_sight_markers: true

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ScannabilityMoveIt
      planning_group: *planning_group
      sensor_frame_name: tcp
      min_dist: 0.0
      max_dist: 0.5
      opt_dist: 0.1
      min_angle: 0.0
      max_angle: 0.3
      opt_angle: 0.0
      sensor_fov_x: 0.8
      sensor_fov_y: 0.45


display:
  name: ROSDisplay
  collision_mesh_filename: *collision_mesh_filename
  kinematic_base_frame: base_link
  marker_scale: 0.05
  use_full_color_range: true
  hue_low_score: 0.0
  hue_high_score: 180.0

target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_ros/demo/config/part.pcd

logger:
  name: BoostProgressConsoleLogger
